<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Conversations\Commands\DeleteConversaion\DeleteConversation.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
	<PackageReference Include="System.DirectoryServices.AccountManagement" Version="8.0.0" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AiChat.Domain\AiChat.Domain.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Entities\" />
    <Folder Include="Users\Queries\GetUser\" />
  </ItemGroup>

</Project>
